export const GET_USER_DATA = 'GET_USER_DATA';
export const ARTIST_SEARCH = 'ARTIST_SEARCH';
export const ALBUMS_LOADING = 'ALBUMS_LOADING';
export const LOAD_ARTIST_ALBUMS = 'LOAD_ARTIST_ALBUMS';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const CLEAR_ALBUMS_DATA = 'CLEAR_ALBUMS_DATA';